import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation-bar/header"; // adjust path
import Footer from "@/components/navigation-bar/footer"; // adjust path

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "JVic Art",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
        <Header /> {/* Rose-themed sticky header */}
        <main className="flex-grow">{children}</main>
        <Footer /> {/* Rose -themed centered footer with social icons */}
        </body>
        </html>
    );
}
